/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Introduction;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Senam
 */
public class FormStagaire extends javax.swing.JFrame {

    /**
     * Creates new form FormStagaire
     */
    public FormStagaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtmat = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtmoyenne = new javax.swing.JTextField();
        txtdateNaiss = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableStg = new javax.swing.JTable();
        btnPremier = new javax.swing.JButton();
        btnPrecedent = new javax.swing.JButton();
        btnSuivant = new javax.swing.JButton();
        btnDernier = new javax.swing.JButton();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btnRecherche = new javax.swing.JButton();
        btnAffiche = new javax.swing.JButton();
        txtRecherche = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtmat.setEditable(false);

        jLabel1.setText("Mat :");

        jLabel2.setText("Nom : ");

        jLabel3.setText("Prenom : ");

        jLabel4.setText("Moyenne : ");

        jLabel5.setText("Date de naissance : ");

        TableStg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableStg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableStgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableStg);

        btnPremier.setText("<<");
        btnPremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremierActionPerformed(evt);
            }
        });

        btnPrecedent.setText("<");
        btnPrecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedentActionPerformed(evt);
            }
        });

        btnSuivant.setText(">");
        btnSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantActionPerformed(evt);
            }
        });

        btnDernier.setText(">>");
        btnDernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDernierActionPerformed(evt);
            }
        });

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        jLabel6.setText("Recherche par nom : ");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Mat");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Nom");

        btnRecherche.setText("Recherche");
        btnRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercheActionPerformed(evt);
            }
        });

        btnAffiche.setText("Affiche");
        btnAffiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfficheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmoyenne, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(txtprenom, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(txtnom, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(txtmat, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(txtdateNaiss))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAjouter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModifier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSupprimer))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPremier, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrecedent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSuivant, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDernier, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(txtRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnRecherche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAffiche)))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmoyenne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPremier)
                            .addComponent(btnPrecedent)
                            .addComponent(btnSuivant)
                            .addComponent(btnDernier))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAjouter)
                            .addComponent(btnModifier)
                            .addComponent(btnSupprimer))
                        .addGap(56, 56, 56))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jRadioButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnRecherche)
                                        .addComponent(btnAffiche))
                                    .addComponent(txtRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            
            //connection
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
//              String path = "C:\\Users\\Senam\\Desktop\\dataBase\\dataBase.mdb";
            //String path = "C:\\Users\\Senam\\Desktop\\dataBase\\dataBase.accdb";
            String path = "C:\\Users\\Senam\\Documents\\NetBeansProjects\\stg\\data\\dataBase.accdb";
            String chi = "jdbc:ucanaccess://" + path;
            cnx = DriverManager.getConnection(chi);
            St = cnx.createStatement();

            buttonGroup1.add(jRadioButton1);
            buttonGroup1.add(jRadioButton2);

            jRadioButton1.setSelected(true);
              
            dt = new DefaultTableModel();
            dt.addColumn("mat");
            dt.addColumn("nom");
            dt.addColumn("prenom");
            dt.addColumn("moyenne");
            dt.addColumn("dateNaissance");
            TableStg.setModel(dt);
            
            AfficherStagaire();

        }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null, "Erreur de connexion\n"+ e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnPremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremierActionPerformed
        // TODO add your handling code here:
        try{
            i = 0;
            DeplacerStagiaire(i);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur de premiere stagaire\n"+ e.getMessage());

        }
    }//GEN-LAST:event_btnPremierActionPerformed

    private void btnPrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedentActionPerformed
        // TODO add your handling code here:
        
        try{
            i--;
            DeplacerStagiaire(i);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur de suivant stagaire\n"+ e.getMessage());

        }
    }//GEN-LAST:event_btnPrecedentActionPerformed

    private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
        // TODO add your handling code here:
        try{
            i++;
            DeplacerStagiaire(i);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur de precedent stagaire\n"+ e.getMessage());

        }
    }//GEN-LAST:event_btnSuivantActionPerformed

    private void btnDernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDernierActionPerformed
        // TODO add your handling code here:
        try{
            i = dt.getRowCount() - 1;
            DeplacerStagiaire(i);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur de Dernier stagaire\n"+ e.getMessage());

        }
    }//GEN-LAST:event_btnDernierActionPerformed

    private void TableStgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableStgMouseClicked
        try{
            i = TableStg.getSelectedRow();
            DeplacerStagiaire(i);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur selectionnee stg\n"+ e.getMessage());

        }
    }//GEN-LAST:event_TableStgMouseClicked

    
    //ajouter
    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "Insert into stg Values(Null,'"+ txtnom.getText()+"','"+ txtprenom.getText() +"','"+txtmoyenne.getText()+"','"+txtdateNaiss.getText()+"')";
            System.out.print(sql);
            St.executeUpdate(sql);
            AfficherStagaire();
            VideTxt();
            JOptionPane.showMessageDialog(null,"stagaire add \n" + sql);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur d'ajoute stagaire\n"+ e.getMessage());

        }
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE stg SET nom ='"+txtnom.getText()+"', prenom = '"+txtprenom.getText()+"', moyenne = '"+txtmoyenne.getText()+"',dateNaiss='"+txtdateNaiss.getText()+"' WHERE mat = "+txtmat.getText()+" ";
            St.executeUpdate(sql);
            AfficherStagaire();
            VideTxt();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur de modification stagaire\n"+ e.getMessage());
        }
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:
                try{
            String sql = "DELETE FROM stg WHERE mat = "+txtmat.getText()+"";
            St.executeUpdate(sql);
            VideTxt();
            AfficherStagaire();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur de suppression stagaire\n"+ e.getMessage());
        }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    //recherche
    private void btnRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercheActionPerformed
        // TODO add your handling code here:
        
        try{
           dt.setRowCount(0);
           if(jRadioButton1.isSelected() == true){
               String sql = "SELECT * FROM stg WHERE stg.mat = "+txtRecherche.getText()+"";
               Rs = St.executeQuery(sql);
           }
           else{
               
                String sql = "SELECT * FROM stg WHERE stg.nom = '"+txtRecherche.getText()+"'";
                Rs = St.executeQuery(sql);
                
           }   
           
           while(Rs.next()){
               mat = Rs.getInt(1);
               nom = Rs.getString(2);
               prenom = Rs.getString(3);
               moyenne = Rs.getDouble(4);
               dateNaiss = Rs.getDate(5);
               
               Object[] stg = {mat,nom,prenom,moyenne,dateNaiss};
               dt.addRow(stg);
           }
           
           if(dt.getRowCount() == 0){
               JOptionPane.showMessageDialog(null,"Pas de stg trouve");
           }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur de recherche stagaire\n"+ e.getMessage());

        }

    }//GEN-LAST:event_btnRechercheActionPerformed

    private void btnAfficheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfficheActionPerformed
        // TODO add your handling code here:
        AfficherStagaire();
    }//GEN-LAST:event_btnAfficheActionPerformed

    
    // remplire les champs
    private void DeplacerStagiaire(int i){
        try{
            if(i == 0){
                btnPrecedent.setEnabled(false);
                btnSuivant.setEnabled(true);
            }
            else if(i == dt.getRowCount() -1){
                btnPrecedent.setEnabled(true);
                btnSuivant.setEnabled(false); 
            }
            else{
                btnPrecedent.setEnabled(true);
                btnSuivant.setEnabled(true);
            }
            txtmat.setText(dt.getValueAt(i, 0).toString());
            txtnom.setText(dt.getValueAt(i, 1).toString());
            txtprenom.setText(dt.getValueAt(i, 2).toString());
            txtmoyenne.setText(dt.getValueAt(i, 3).toString());
            txtdateNaiss.setText(dt.getValueAt(i, 4).toString());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur de deplacement stagaire\n"+ e.getMessage());

        }
    }
    // procedure 
    private void AfficherStagaire(){
        try{
           dt.setRowCount(0);
           Rs = St.executeQuery("Select * from stg");
           
           while(Rs.next()){
               mat = Rs.getInt("mat");
               nom = Rs.getString("nom");
               prenom = Rs.getString("prenom");
               moyenne = Rs.getDouble("moyenne");
               dateNaiss = Rs.getDate("dateNaiss");
               
               Object[] stg = {mat,nom,prenom,moyenne,dateNaiss};
               dt.addRow(stg);
           }
           
        }
        catch(Exception s){
            JOptionPane.showMessageDialog(null, "Erreur d'affichage stagaire\n"+ s.getMessage());
 
        }
    }
    //metre les txt en value
    private void VideTxt(){
        txtmat.setText("");
        txtnom.setText("");
        txtprenom.setText("");
        txtmoyenne.setText("");
        txtdateNaiss.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormStagaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormStagaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormStagaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormStagaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormStagaire().setVisible(true);
            }
        });
    }
    
    //declaration des variables
    private Connection cnx;
    private Statement St;
    private ResultSet Rs;
    private DefaultTableModel dt;
    private int mat;
    private String nom, prenom;
    private double moyenne;
    private Date dateNaiss;
    private int i;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableStg;
    private javax.swing.JButton btnAffiche;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnDernier;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnPrecedent;
    private javax.swing.JButton btnPremier;
    private javax.swing.JButton btnRecherche;
    private javax.swing.JButton btnSuivant;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtRecherche;
    private javax.swing.JTextField txtdateNaiss;
    private javax.swing.JTextField txtmat;
    private javax.swing.JTextField txtmoyenne;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    // End of variables declaration//GEN-END:variables
}
